#!/bin/bash
#PBS -P mb26
#PBS -l ncpus=48,ngpus=4,mem=96gb
#PBS -l storage=scratch/mb26
#PBS -l walltime=4:00:00
#PBS -q gpuvolta
#PBS -m be
#PBS -l wd

cd
source v100_py3.12/bin/activate

cd /scratch/mb26/tv8394/workspace/improved-diffusion

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Job started on $(hostname)" >> log.txt
echo "[$(date '+%Y-%m-%d %H:%M:%S')] GPUs: $(nvidia-smi --query-gpu=name --format=csv,noheader | tr '\n' ',')" >> log.txt

export OPENAI_LOGDIR="simple-shapes-5k-checkpoints"
rm -rf $OPENAI_LOGDIR
MODEL_FLAGS="--image_size 64 --num_channels 64 --num_res_blocks 3"
DIFFUSION_FLAGS="--diffusion_steps 1000 --noise_schedule linear"
TRAIN_FLAGS="--lr 1e-4 --batch_size 256 --lr_anneal_steps 250000 --resume_checkpoint simple-shapes-5k-checkpoints/model080000.pt"

NUM_GPUS=4
mpiexec -n $NUM_GPUS python scripts/image_train.py --data_dir simple-shapes-5k $MODEL_FLAGS $DIFFUSION_FLAGS $TRAIN_FLAGS
