#!/bin/bash
#PBS -P mb26
#PBS -l ncpus=48,ngpus=4,mem=96gb
#PBS -l storage=scratch/mb26
#PBS -l walltime=8:00:00
#PBS -q gpuhopper
#PBS -m be
#PBS -l wd

cd workspace/improved-diffusion

export OPENAI_LOGDIR="simple-shapes-5k-checkpoints"
rm -rf $OPENAI_LOGDIR
MODEL_FLAGS="--image_size 64 --num_channels 128 --num_res_blocks 3"
DIFFUSION_FLAGS="--diffusion_steps 1000 --noise_schedule linear"
TRAIN_FLAGS="--lr 1e-4 --batch_size 256 --lr_anneal_steps 250000"

NUM_GPUS=4
mpiexec -n $NUM_GPUS python scripts/image_train.py --data_dir simple-shapes-5k $MODEL_FLAGS $DIFFUSION_FLAGS $TRAIN_FLAGS
