#!/bin/bash
#PBS -P mb26
#PBS -l ncpus=24,ngpus=2,mem=48gb
#PBS -l storage=scratch/mb26
#PBS -l walltime=4:00:00
#PBS -q gpuvolta
#PBS -m be
#PBS -l wd

cd
source v100_py3.12/bin/activate

cd /scratch/mb26/tv8394/workspace/improved-diffusion

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Job started on $(hostname)" >> log.txt
echo "[$(date '+%Y-%m-%d %H:%M:%S')] GPUs: $(nvidia-smi --query-gpu=name --format=csv,noheader | tr '\n' ',')" >> log.txt

MODEL_FLAGS="--image_size 64 --num_channels 64 --num_res_blocks 3"
DIFFUSION_FLAGS="--diffusion_steps 1000 --noise_schedule linear --num_samples 10000 --timestep_respacing 100"

NUM_GPUS=2

for STEP in 020000 030000 040000 050000 060000 070000 080000 090000 100000 110000 120000 130000 140000 150000 160000; do
    CKPT="simple-shapes-5k-checkpoints/ema_0.9999_${STEP}.pt"
    export OPENAI_LOGDIR="simple-shapes-5k-checkpoints-${STEP}s-sampling-100steps"
    echo "=== Sampling from step ${STEP} ==="
    mpiexec -n $NUM_GPUS  python scripts/image_sample.py --model_path $CKPT $MODEL_FLAGS $DIFFUSION_FLAGS
done